### ISSUE TITLE
更新dev到最新版之后，waline评论不显示

### ISSUE THREAD

**Issue by lengxi911** [DuoSco/Hexo-theme-solitude#102]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

更新到最新版本后waline评论不显示

![image](https://github.com/DuoSco/Hexo-theme-solitude/assets/103512447/caf2b5de-b5b7-4907-a8b5-6062ba5ded2f)

![image](https://github.com/DuoSco/Hexo-theme-solitude/assets/103512447/4013251e-7415-453e-9b8f-0534b500f7cb)

### 终端日志 📒

<此处粘贴终端日志>

**Comment by wleelw** [comment]
已修复，请重新拉取
