### ISSUE TITLE
安知鱼music界面

### ISSUE THREAD

**Issue by xiaobaisky** [DuoSco/Hexo-theme-solitude#53]
![1701850748009](https://github.com/DuoSco/Hexo-theme-solitude/assets/51472079/84e4442a-868a-42ff-8a00-7a55d2310731)

**Comment by wleelw** [comment]
已立项，敬请期待

**Comment by yife68** [comment]
开发难点延缓，待调试测试版

**Comment by yife68** [comment]
目前已经合理解决难点实现，进入细节调整以及PE端适配。
暂时性推出阉割的第一版，后期会继续适配以及新增该功能的拓展项。

> 最新功能进度：70%

![微信截图_20231210214111](https://github.com/DuoSco/Hexo-theme-solitude/assets/36876386/e821e07d-6552-4301-8555-26f63549ff62)
![微信图片_20231210214445](https://github.com/DuoSco/Hexo-theme-solitude/assets/36876386/680f4220-0c5f-47b2-9409-9f543a585cf1)

**Comment by lazyingman** [comment]
音乐馆进度条拖不动

**Comment by yife68** [comment]
> 音乐馆进度条拖不动

你看下是否使用了swpp功能，在此前已知是因为swpp缓存机制导致的问题。

**Comment by everfu** [comment]
请不要误会这个issue，此issue仅用户提出，实现后的效果不是安知鱼主题的预览，自行对比

实现相同功能而已

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/13ab5db6-ea17-4660-88f4-3eca592b0dd2">
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/c84f5937-5f4b-4960-9db9-d93a35e2d922">
