### ISSUE TITLE
heo ai摘要样式

### ISSUE THREAD

**Issue by xiaobaisky** [DuoSco/Hexo-theme-solitude#54]
![1702285277487](https://github.com/DuoSco/Hexo-theme-solitude/assets/51472079/078b305f-ffdf-47d4-9f52-f1322f589663)

**Comment by wleelw** [comment]
dev分支已经提交，具体请自行体验，有问题提出

**Comment by xiaobaisky** [comment]
ok，辛苦

**Comment by baiyinet** [comment]
Ai摘要只能dev版本嘛稳定版能不能本地ai

**Comment by everfu** [comment]
> Ai摘要只能dev版本嘛稳定版能不能本地ai

可以
