### ISSUE TITLE
请添加以下几处

### ISSUE THREAD

**Issue by xiaobaisky** [DuoSco/Hexo-theme-solitude#59]
![1702391733121](https://github.com/DuoSco/Hexo-theme-solitude/assets/51472079/9055ba8b-343a-4552-bb3a-50f5bea32611)

**Comment by wleelw** [comment]
隐私政策不添加，其他已完成

**Comment by xiaobaisky** [comment]
ok

**Comment by RicharPao** [comment]
隐私政策自己加一个也可以
