### ISSUE TITLE
Nunjucks 扩展?

### ISSUE THREAD

**Issue by MGHYGitHub** [DuoSco/Hexo-theme-solitude#63]
看起来是 Nunjucks 模板中包含了一个未知的块标签 u，并且该标签在 Nunjucks 中没有被识别。

可能是因为 Nunjucks 不认识 u 这个标签。在 Nunjucks 中，标签通常需要通过扩展（extension）来添加。
请大大添加引入了支持 u 标签的 Nunjucks 扩展。

![image](https://github.com/DuoSco/Hexo-theme-solitude/assets/113328471/1984d571-97cd-4298-aa60-1f8b97091708)

**Comment by wleelw** [comment]
dev分支已加入当前内容，如急需可先升级dev，或者待后续测试完成体验稳定版
