### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by lisuid** [DuoSco/Hexo-theme-solitude#72]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

添加swpp刷新缓存按钮
添加留言板功能
多开发新功能

### 终端日志 📒

<此处粘贴终端日志>

**Comment by wleelw** [comment]
留言板属自定义页面，刷新缓存属于自定义内容，主题不提供
